branch-defaults:
  default:
    environment: shop49-dev
  master:
    environment: shop49-dev
global:
  application_name: shop49
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-southeast-1
  profile: eb-cli
